// Code generated by protoc-gen-plain-go. DO NOT EDIT.
package v1alpha1

type Registry struct {
	Name        string     `json:"name"`
	Description string     `json:"description"`
	Packages    []*Package `json:"packages"`
}

type Package struct {
	Name        string  `json:"name"`
	Description string  `json:"description"`
	Files       []*File `json:"files"`
	Schema      *Schema `json:"schema"`
}

type Schema struct {
	Fields []*Field `json:"fields"`
}

type Field struct {
	Name        string                     `json:"name"`
	Type        *interface{}               `json:"type"`
	Items       *Field_SubField            `json:"items"`
	Description *string                    `json:"description"`
	Default     *Google_Protobuf_Value     `json:"default"`
	Enum        *Google_Protobuf_ListValue `json:"enum"`
}

type FieldSubField struct {
	Type *interface{}               `json:"type"`
	Enum *Google_Protobuf_ListValue `json:"enum"`
}

type File struct {
	Path    string      `json:"path"`
	Target  string      `json:"target"`
	Raw     *[]byte     `json:"raw"`
	Type    interface{} `json:"type"`
	Content *string     `json:"content"`
}
