// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: skiff/cmd/v1alpha1/commands.proto

package v1alpha1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	v1alpha1 "github.com/skiff-sh/skiff/api/go/skiff/registry/v1alpha1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The request data needed to add a package.
type AddPackageRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// An absolute filepath to the project root. This is used as the root directory to place all files within.
	Root string `protobuf:"bytes,1,opt,name=root,proto3" json:"root,omitempty"`
	// The list of file paths to packages or http(s) URLs. HTTP(s) URLs must start with "http(s)://", otherwise, it's treated as a filepath.
	Packages []string `protobuf:"bytes,2,rep,name=packages,proto3" json:"packages,omitempty"`
	// The list of permissions available to plugins that are called within the packages. If none are specified, no permissions are granted to the user's system.
	PluginPermissions []v1alpha1.PackagePermissions_Plugin `protobuf:"varint,3,rep,packed,name=plugin_permissions,proto3,enum=skiff.registry.v1alpha1.PackagePermissions_Plugin" json:"plugin_permissions,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *AddPackageRequest) Reset() {
	*x = AddPackageRequest{}
	mi := &file_skiff_cmd_v1alpha1_commands_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddPackageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddPackageRequest) ProtoMessage() {}

func (x *AddPackageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_skiff_cmd_v1alpha1_commands_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddPackageRequest.ProtoReflect.Descriptor instead.
func (*AddPackageRequest) Descriptor() ([]byte, []int) {
	return file_skiff_cmd_v1alpha1_commands_proto_rawDescGZIP(), []int{0}
}

func (x *AddPackageRequest) GetRoot() string {
	if x != nil {
		return x.Root
	}
	return ""
}

func (x *AddPackageRequest) GetPackages() []string {
	if x != nil {
		return x.Packages
	}
	return nil
}

func (x *AddPackageRequest) GetPluginPermissions() []v1alpha1.PackagePermissions_Plugin {
	if x != nil {
		return x.PluginPermissions
	}
	return nil
}

// The response data for AddPackageRequest.
type AddPackageResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// A list of file diffs that should be applied to the user's machine. These use the absolute path using the "root" field passed into the request.
	// There is a single unified diff per file.
	UnifiedDiffs  []string `protobuf:"bytes,1,rep,name=unified_diffs,proto3" json:"unified_diffs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddPackageResponse) Reset() {
	*x = AddPackageResponse{}
	mi := &file_skiff_cmd_v1alpha1_commands_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddPackageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddPackageResponse) ProtoMessage() {}

func (x *AddPackageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_skiff_cmd_v1alpha1_commands_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddPackageResponse.ProtoReflect.Descriptor instead.
func (*AddPackageResponse) Descriptor() ([]byte, []int) {
	return file_skiff_cmd_v1alpha1_commands_proto_rawDescGZIP(), []int{1}
}

func (x *AddPackageResponse) GetUnifiedDiffs() []string {
	if x != nil {
		return x.UnifiedDiffs
	}
	return nil
}

type ListPackagesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The URLs or local file paths to packages.
	Packages      []string `protobuf:"bytes,1,rep,name=packages,proto3" json:"packages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPackagesRequest) Reset() {
	*x = ListPackagesRequest{}
	mi := &file_skiff_cmd_v1alpha1_commands_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPackagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPackagesRequest) ProtoMessage() {}

func (x *ListPackagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_skiff_cmd_v1alpha1_commands_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPackagesRequest.ProtoReflect.Descriptor instead.
func (*ListPackagesRequest) Descriptor() ([]byte, []int) {
	return file_skiff_cmd_v1alpha1_commands_proto_rawDescGZIP(), []int{2}
}

func (x *ListPackagesRequest) GetPackages() []string {
	if x != nil {
		return x.Packages
	}
	return nil
}

type ListPackagesResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// A list of packages from the registry. If the file is of type "plugin" the "source" will not be populated.
	Packages      []*v1alpha1.Package `protobuf:"bytes,1,rep,name=packages,proto3" json:"packages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPackagesResponse) Reset() {
	*x = ListPackagesResponse{}
	mi := &file_skiff_cmd_v1alpha1_commands_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPackagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPackagesResponse) ProtoMessage() {}

func (x *ListPackagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_skiff_cmd_v1alpha1_commands_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPackagesResponse.ProtoReflect.Descriptor instead.
func (*ListPackagesResponse) Descriptor() ([]byte, []int) {
	return file_skiff_cmd_v1alpha1_commands_proto_rawDescGZIP(), []int{3}
}

func (x *ListPackagesResponse) GetPackages() []*v1alpha1.Package {
	if x != nil {
		return x.Packages
	}
	return nil
}

var File_skiff_cmd_v1alpha1_commands_proto protoreflect.FileDescriptor

const file_skiff_cmd_v1alpha1_commands_proto_rawDesc = "" +
	"\n" +
	"!skiff/cmd/v1alpha1/commands.proto\x12\x12skiff.cmd.v1alpha1\x1a\x1bbuf/validate/validate.proto\x1a&skiff/registry/v1alpha1/registry.proto\"\xba\x01\n" +
	"\x11AddPackageRequest\x12\x1b\n" +
	"\x04root\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x04root\x12$\n" +
	"\bpackages\x18\x02 \x03(\tB\b\xbaH\x05\x92\x01\x02\b\x01R\bpackages\x12b\n" +
	"\x12plugin_permissions\x18\x03 \x03(\x0e22.skiff.registry.v1alpha1.PackagePermissions.PluginR\x12plugin_permissions\":\n" +
	"\x12AddPackageResponse\x12$\n" +
	"\runified_diffs\x18\x01 \x03(\tR\runified_diffs\"1\n" +
	"\x13ListPackagesRequest\x12\x1a\n" +
	"\bpackages\x18\x01 \x03(\tR\bpackages\"T\n" +
	"\x14ListPackagesResponse\x12<\n" +
	"\bpackages\x18\x01 \x03(\v2 .skiff.registry.v1alpha1.PackageR\bpackagesB\xc6\x01\n" +
	"\x16com.skiff.cmd.v1alpha1B\rCommandsProtoP\x01Z3github.com/skiff-sh/skiff/api/go/skiff/cmd/v1alpha1\xa2\x02\x03SCX\xaa\x02\x12Skiff.Cmd.V1alpha1\xca\x02\x12Skiff\\Cmd\\V1alpha1\xe2\x02\x1eSkiff\\Cmd\\V1alpha1\\GPBMetadata\xea\x02\x14Skiff::Cmd::V1alpha1b\x06proto3"

var (
	file_skiff_cmd_v1alpha1_commands_proto_rawDescOnce sync.Once
	file_skiff_cmd_v1alpha1_commands_proto_rawDescData []byte
)

func file_skiff_cmd_v1alpha1_commands_proto_rawDescGZIP() []byte {
	file_skiff_cmd_v1alpha1_commands_proto_rawDescOnce.Do(func() {
		file_skiff_cmd_v1alpha1_commands_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_skiff_cmd_v1alpha1_commands_proto_rawDesc), len(file_skiff_cmd_v1alpha1_commands_proto_rawDesc)))
	})
	return file_skiff_cmd_v1alpha1_commands_proto_rawDescData
}

var file_skiff_cmd_v1alpha1_commands_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_skiff_cmd_v1alpha1_commands_proto_goTypes = []any{
	(*AddPackageRequest)(nil),               // 0: skiff.cmd.v1alpha1.AddPackageRequest
	(*AddPackageResponse)(nil),              // 1: skiff.cmd.v1alpha1.AddPackageResponse
	(*ListPackagesRequest)(nil),             // 2: skiff.cmd.v1alpha1.ListPackagesRequest
	(*ListPackagesResponse)(nil),            // 3: skiff.cmd.v1alpha1.ListPackagesResponse
	(v1alpha1.PackagePermissions_Plugin)(0), // 4: skiff.registry.v1alpha1.PackagePermissions.Plugin
	(*v1alpha1.Package)(nil),                // 5: skiff.registry.v1alpha1.Package
}
var file_skiff_cmd_v1alpha1_commands_proto_depIdxs = []int32{
	4, // 0: skiff.cmd.v1alpha1.AddPackageRequest.plugin_permissions:type_name -> skiff.registry.v1alpha1.PackagePermissions.Plugin
	5, // 1: skiff.cmd.v1alpha1.ListPackagesResponse.packages:type_name -> skiff.registry.v1alpha1.Package
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_skiff_cmd_v1alpha1_commands_proto_init() }
func file_skiff_cmd_v1alpha1_commands_proto_init() {
	if File_skiff_cmd_v1alpha1_commands_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_skiff_cmd_v1alpha1_commands_proto_rawDesc), len(file_skiff_cmd_v1alpha1_commands_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_skiff_cmd_v1alpha1_commands_proto_goTypes,
		DependencyIndexes: file_skiff_cmd_v1alpha1_commands_proto_depIdxs,
		MessageInfos:      file_skiff_cmd_v1alpha1_commands_proto_msgTypes,
	}.Build()
	File_skiff_cmd_v1alpha1_commands_proto = out.File
	file_skiff_cmd_v1alpha1_commands_proto_goTypes = nil
	file_skiff_cmd_v1alpha1_commands_proto_depIdxs = nil
}
