// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: skiff/cmd/v1alpha1/commands.proto

package v1alpha1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"

	v1alpha1 "github.com/skiff-sh/skiff/api/go/skiff/registry/v1alpha1"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort

	_ = v1alpha1.PackagePermissions_Plugin(0)
)

// Validate checks the field values on AddPackageRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *AddPackageRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on AddPackageRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// AddPackageRequestMultiError, or nil if none found.
func (m *AddPackageRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *AddPackageRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Root

	if len(errors) > 0 {
		return AddPackageRequestMultiError(errors)
	}

	return nil
}

// AddPackageRequestMultiError is an error wrapping multiple validation errors
// returned by AddPackageRequest.ValidateAll() if the designated constraints
// aren't met.
type AddPackageRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m AddPackageRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m AddPackageRequestMultiError) AllErrors() []error { return m }

// AddPackageRequestValidationError is the validation error returned by
// AddPackageRequest.Validate if the designated constraints aren't met.
type AddPackageRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e AddPackageRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e AddPackageRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e AddPackageRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e AddPackageRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e AddPackageRequestValidationError) ErrorName() string {
	return "AddPackageRequestValidationError"
}

// Error satisfies the builtin error interface
func (e AddPackageRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sAddPackageRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = AddPackageRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = AddPackageRequestValidationError{}

// Validate checks the field values on AddPackageResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *AddPackageResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on AddPackageResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// AddPackageResponseMultiError, or nil if none found.
func (m *AddPackageResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *AddPackageResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return AddPackageResponseMultiError(errors)
	}

	return nil
}

// AddPackageResponseMultiError is an error wrapping multiple validation errors
// returned by AddPackageResponse.ValidateAll() if the designated constraints
// aren't met.
type AddPackageResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m AddPackageResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m AddPackageResponseMultiError) AllErrors() []error { return m }

// AddPackageResponseValidationError is the validation error returned by
// AddPackageResponse.Validate if the designated constraints aren't met.
type AddPackageResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e AddPackageResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e AddPackageResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e AddPackageResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e AddPackageResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e AddPackageResponseValidationError) ErrorName() string {
	return "AddPackageResponseValidationError"
}

// Error satisfies the builtin error interface
func (e AddPackageResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sAddPackageResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = AddPackageResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = AddPackageResponseValidationError{}

// Validate checks the field values on ListPackagesRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ListPackagesRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListPackagesRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListPackagesRequestMultiError, or nil if none found.
func (m *ListPackagesRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *ListPackagesRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return ListPackagesRequestMultiError(errors)
	}

	return nil
}

// ListPackagesRequestMultiError is an error wrapping multiple validation
// errors returned by ListPackagesRequest.ValidateAll() if the designated
// constraints aren't met.
type ListPackagesRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListPackagesRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListPackagesRequestMultiError) AllErrors() []error { return m }

// ListPackagesRequestValidationError is the validation error returned by
// ListPackagesRequest.Validate if the designated constraints aren't met.
type ListPackagesRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListPackagesRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListPackagesRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListPackagesRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListPackagesRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListPackagesRequestValidationError) ErrorName() string {
	return "ListPackagesRequestValidationError"
}

// Error satisfies the builtin error interface
func (e ListPackagesRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListPackagesRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListPackagesRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListPackagesRequestValidationError{}

// Validate checks the field values on ListPackagesResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ListPackagesResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListPackagesResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListPackagesResponseMultiError, or nil if none found.
func (m *ListPackagesResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *ListPackagesResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetPackages() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ListPackagesResponseValidationError{
						field:  fmt.Sprintf("Packages[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ListPackagesResponseValidationError{
						field:  fmt.Sprintf("Packages[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ListPackagesResponseValidationError{
					field:  fmt.Sprintf("Packages[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return ListPackagesResponseMultiError(errors)
	}

	return nil
}

// ListPackagesResponseMultiError is an error wrapping multiple validation
// errors returned by ListPackagesResponse.ValidateAll() if the designated
// constraints aren't met.
type ListPackagesResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListPackagesResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListPackagesResponseMultiError) AllErrors() []error { return m }

// ListPackagesResponseValidationError is the validation error returned by
// ListPackagesResponse.Validate if the designated constraints aren't met.
type ListPackagesResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListPackagesResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListPackagesResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListPackagesResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListPackagesResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListPackagesResponseValidationError) ErrorName() string {
	return "ListPackagesResponseValidationError"
}

// Error satisfies the builtin error interface
func (e ListPackagesResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListPackagesResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListPackagesResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListPackagesResponseValidationError{}
