// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: skiff/cmd/v1alpha1/commands.proto

package v1alpha1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	v1alpha1 "github.com/skiff-sh/api/go/skiff/registry/v1alpha1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Generates all files within the package and returns the diffs that would result from them being written. Packages hold both templates and WASM plugins that are
// executed locally to edit local files.
type AddPackageRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// An absolute filepath to the project root. This is used as the root for all plugin file reads and the base reference path for all file outputs.
	ProjectRoot string `protobuf:"bytes,1,opt,name=project_root,proto3" json:"project_root,omitempty"`
	// The list of file paths to packages or http(s) URLs. HTTP(s) URLs must start with "http(s)://", otherwise, it's treated as a filepath.
	Packages []string `protobuf:"bytes,2,rep,name=packages,proto3" json:"packages,omitempty"`
	// The list of permissions available to plugins that are called within the packages. If none are specified, no permissions are granted to the user's system.
	PluginPermissions []v1alpha1.PackagePermissions_Plugin `protobuf:"varint,3,rep,packed,name=plugin_permissions,proto3,enum=skiff.registry.v1alpha1.PackagePermissions_Plugin" json:"plugin_permissions,omitempty"`
	// The data needed by the package. The schema is retrieved via the "view packages" call.
	Data          *structpb.Struct `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddPackageRequest) Reset() {
	*x = AddPackageRequest{}
	mi := &file_skiff_cmd_v1alpha1_commands_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddPackageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddPackageRequest) ProtoMessage() {}

func (x *AddPackageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_skiff_cmd_v1alpha1_commands_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddPackageRequest.ProtoReflect.Descriptor instead.
func (*AddPackageRequest) Descriptor() ([]byte, []int) {
	return file_skiff_cmd_v1alpha1_commands_proto_rawDescGZIP(), []int{0}
}

func (x *AddPackageRequest) GetProjectRoot() string {
	if x != nil {
		return x.ProjectRoot
	}
	return ""
}

func (x *AddPackageRequest) GetPackages() []string {
	if x != nil {
		return x.Packages
	}
	return nil
}

func (x *AddPackageRequest) GetPluginPermissions() []v1alpha1.PackagePermissions_Plugin {
	if x != nil {
		return x.PluginPermissions
	}
	return nil
}

func (x *AddPackageRequest) GetData() *structpb.Struct {
	if x != nil {
		return x.Data
	}
	return nil
}

// The response data for AddPackageRequest.
type AddPackageResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// A list of file diffs that should be applied to the user's machine. These use the absolute path using the "project_root" field passed into the request.
	// There is a single unified diff per file.
	UnifiedDiffs  []string `protobuf:"bytes,1,rep,name=unified_diffs,proto3" json:"unified_diffs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddPackageResponse) Reset() {
	*x = AddPackageResponse{}
	mi := &file_skiff_cmd_v1alpha1_commands_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddPackageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddPackageResponse) ProtoMessage() {}

func (x *AddPackageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_skiff_cmd_v1alpha1_commands_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddPackageResponse.ProtoReflect.Descriptor instead.
func (*AddPackageResponse) Descriptor() ([]byte, []int) {
	return file_skiff_cmd_v1alpha1_commands_proto_rawDescGZIP(), []int{1}
}

func (x *AddPackageResponse) GetUnifiedDiffs() []string {
	if x != nil {
		return x.UnifiedDiffs
	}
	return nil
}

// List all packages within a set of registries. These packages do not include the contents of the files. To get more details about a package use the view package
// call.
type ListPackagesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The URLs or local file paths to registries e.g. ./.skiff/registry.json.
	Registries    []string `protobuf:"bytes,1,rep,name=registries,proto3" json:"registries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPackagesRequest) Reset() {
	*x = ListPackagesRequest{}
	mi := &file_skiff_cmd_v1alpha1_commands_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPackagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPackagesRequest) ProtoMessage() {}

func (x *ListPackagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_skiff_cmd_v1alpha1_commands_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPackagesRequest.ProtoReflect.Descriptor instead.
func (*ListPackagesRequest) Descriptor() ([]byte, []int) {
	return file_skiff_cmd_v1alpha1_commands_proto_rawDescGZIP(), []int{2}
}

func (x *ListPackagesRequest) GetRegistries() []string {
	if x != nil {
		return x.Registries
	}
	return nil
}

type ListPackagesResponse struct {
	state         protoimpl.MessageState                 `protogen:"open.v1"`
	Packages      []*ListPackagesResponse_PackagePreview `protobuf:"bytes,1,rep,name=packages,proto3" json:"packages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPackagesResponse) Reset() {
	*x = ListPackagesResponse{}
	mi := &file_skiff_cmd_v1alpha1_commands_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPackagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPackagesResponse) ProtoMessage() {}

func (x *ListPackagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_skiff_cmd_v1alpha1_commands_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPackagesResponse.ProtoReflect.Descriptor instead.
func (*ListPackagesResponse) Descriptor() ([]byte, []int) {
	return file_skiff_cmd_v1alpha1_commands_proto_rawDescGZIP(), []int{3}
}

func (x *ListPackagesResponse) GetPackages() []*ListPackagesResponse_PackagePreview {
	if x != nil {
		return x.Packages
	}
	return nil
}

type ListPackagesResponse_PackagePreview struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The name of the file with the extension.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// The type of the file.
	Type v1alpha1.File_Type `protobuf:"varint,2,opt,name=type,proto3,enum=skiff.registry.v1alpha1.File_Type" json:"type,omitempty"`
	// The registry that this package belongs to.
	Registry string `protobuf:"bytes,3,opt,name=registry,proto3" json:"registry,omitempty"`
	// A short description of the package.
	Description *string `protobuf:"bytes,4,opt,name=description,proto3,oneof" json:"description,omitempty"`
	// Either the http(s) URL or the local file path to add/view the package.
	Path string `protobuf:"bytes,5,opt,name=path,proto3" json:"path,omitempty"`
	// The schema for the data required to add this package.
	JsonSchema    string `protobuf:"bytes,6,opt,name=json_schema,proto3" json:"json_schema,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPackagesResponse_PackagePreview) Reset() {
	*x = ListPackagesResponse_PackagePreview{}
	mi := &file_skiff_cmd_v1alpha1_commands_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPackagesResponse_PackagePreview) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPackagesResponse_PackagePreview) ProtoMessage() {}

func (x *ListPackagesResponse_PackagePreview) ProtoReflect() protoreflect.Message {
	mi := &file_skiff_cmd_v1alpha1_commands_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPackagesResponse_PackagePreview.ProtoReflect.Descriptor instead.
func (*ListPackagesResponse_PackagePreview) Descriptor() ([]byte, []int) {
	return file_skiff_cmd_v1alpha1_commands_proto_rawDescGZIP(), []int{3, 0}
}

func (x *ListPackagesResponse_PackagePreview) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ListPackagesResponse_PackagePreview) GetType() v1alpha1.File_Type {
	if x != nil {
		return x.Type
	}
	return v1alpha1.File_Type(0)
}

func (x *ListPackagesResponse_PackagePreview) GetRegistry() string {
	if x != nil {
		return x.Registry
	}
	return ""
}

func (x *ListPackagesResponse_PackagePreview) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *ListPackagesResponse_PackagePreview) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *ListPackagesResponse_PackagePreview) GetJsonSchema() string {
	if x != nil {
		return x.JsonSchema
	}
	return ""
}

var File_skiff_cmd_v1alpha1_commands_proto protoreflect.FileDescriptor

const file_skiff_cmd_v1alpha1_commands_proto_rawDesc = "" +
	"\n" +
	"!skiff/cmd/v1alpha1/commands.proto\x12\x12skiff.cmd.v1alpha1\x1a\x1bbuf/validate/validate.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a&skiff/registry/v1alpha1/registry.proto\"\xf7\x01\n" +
	"\x11AddPackageRequest\x12+\n" +
	"\fproject_root\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\fproject_root\x12$\n" +
	"\bpackages\x18\x02 \x03(\tB\b\xbaH\x05\x92\x01\x02\b\x01R\bpackages\x12b\n" +
	"\x12plugin_permissions\x18\x03 \x03(\x0e22.skiff.registry.v1alpha1.PackagePermissions.PluginR\x12plugin_permissions\x12+\n" +
	"\x04data\x18\x04 \x01(\v2\x17.google.protobuf.StructR\x04data\":\n" +
	"\x12AddPackageResponse\x12$\n" +
	"\runified_diffs\x18\x01 \x03(\tR\runified_diffs\"5\n" +
	"\x13ListPackagesRequest\x12\x1e\n" +
	"\n" +
	"registries\x18\x01 \x03(\tR\n" +
	"registries\"\xd3\x02\n" +
	"\x14ListPackagesResponse\x12S\n" +
	"\bpackages\x18\x01 \x03(\v27.skiff.cmd.v1alpha1.ListPackagesResponse.PackagePreviewR\bpackages\x1a\xe5\x01\n" +
	"\x0ePackagePreview\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x126\n" +
	"\x04type\x18\x02 \x01(\x0e2\".skiff.registry.v1alpha1.File.TypeR\x04type\x12\x1a\n" +
	"\bregistry\x18\x03 \x01(\tR\bregistry\x12%\n" +
	"\vdescription\x18\x04 \x01(\tH\x00R\vdescription\x88\x01\x01\x12\x12\n" +
	"\x04path\x18\x05 \x01(\tR\x04path\x12 \n" +
	"\vjson_schema\x18\x06 \x01(\tR\vjson_schemaB\x0e\n" +
	"\f_descriptionB\xc0\x01\n" +
	"\x16com.skiff.cmd.v1alpha1B\rCommandsProtoP\x01Z-github.com/skiff-sh/api/go/skiff/cmd/v1alpha1\xa2\x02\x03SCX\xaa\x02\x12Skiff.Cmd.V1alpha1\xca\x02\x12Skiff\\Cmd\\V1alpha1\xe2\x02\x1eSkiff\\Cmd\\V1alpha1\\GPBMetadata\xea\x02\x14Skiff::Cmd::V1alpha1b\x06proto3"

var (
	file_skiff_cmd_v1alpha1_commands_proto_rawDescOnce sync.Once
	file_skiff_cmd_v1alpha1_commands_proto_rawDescData []byte
)

func file_skiff_cmd_v1alpha1_commands_proto_rawDescGZIP() []byte {
	file_skiff_cmd_v1alpha1_commands_proto_rawDescOnce.Do(func() {
		file_skiff_cmd_v1alpha1_commands_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_skiff_cmd_v1alpha1_commands_proto_rawDesc), len(file_skiff_cmd_v1alpha1_commands_proto_rawDesc)))
	})
	return file_skiff_cmd_v1alpha1_commands_proto_rawDescData
}

var file_skiff_cmd_v1alpha1_commands_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_skiff_cmd_v1alpha1_commands_proto_goTypes = []any{
	(*AddPackageRequest)(nil),                   // 0: skiff.cmd.v1alpha1.AddPackageRequest
	(*AddPackageResponse)(nil),                  // 1: skiff.cmd.v1alpha1.AddPackageResponse
	(*ListPackagesRequest)(nil),                 // 2: skiff.cmd.v1alpha1.ListPackagesRequest
	(*ListPackagesResponse)(nil),                // 3: skiff.cmd.v1alpha1.ListPackagesResponse
	(*ListPackagesResponse_PackagePreview)(nil), // 4: skiff.cmd.v1alpha1.ListPackagesResponse.PackagePreview
	(v1alpha1.PackagePermissions_Plugin)(0),     // 5: skiff.registry.v1alpha1.PackagePermissions.Plugin
	(*structpb.Struct)(nil),                     // 6: google.protobuf.Struct
	(v1alpha1.File_Type)(0),                     // 7: skiff.registry.v1alpha1.File.Type
}
var file_skiff_cmd_v1alpha1_commands_proto_depIdxs = []int32{
	5, // 0: skiff.cmd.v1alpha1.AddPackageRequest.plugin_permissions:type_name -> skiff.registry.v1alpha1.PackagePermissions.Plugin
	6, // 1: skiff.cmd.v1alpha1.AddPackageRequest.data:type_name -> google.protobuf.Struct
	4, // 2: skiff.cmd.v1alpha1.ListPackagesResponse.packages:type_name -> skiff.cmd.v1alpha1.ListPackagesResponse.PackagePreview
	7, // 3: skiff.cmd.v1alpha1.ListPackagesResponse.PackagePreview.type:type_name -> skiff.registry.v1alpha1.File.Type
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_skiff_cmd_v1alpha1_commands_proto_init() }
func file_skiff_cmd_v1alpha1_commands_proto_init() {
	if File_skiff_cmd_v1alpha1_commands_proto != nil {
		return
	}
	file_skiff_cmd_v1alpha1_commands_proto_msgTypes[4].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_skiff_cmd_v1alpha1_commands_proto_rawDesc), len(file_skiff_cmd_v1alpha1_commands_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_skiff_cmd_v1alpha1_commands_proto_goTypes,
		DependencyIndexes: file_skiff_cmd_v1alpha1_commands_proto_depIdxs,
		MessageInfos:      file_skiff_cmd_v1alpha1_commands_proto_msgTypes,
	}.Build()
	File_skiff_cmd_v1alpha1_commands_proto = out.File
	file_skiff_cmd_v1alpha1_commands_proto_goTypes = nil
	file_skiff_cmd_v1alpha1_commands_proto_depIdxs = nil
}
