// Code generated by protoc-gen-plain-go. DO NOT EDIT.
package v1alpha1

type Request struct {
	WriteFile *WriteFileRequest `json:"write_file,omitempty"`
}

type Response struct {
	WriteFile *WriteFileResponse `json:"write_file,omitempty"`
}

type WriteFileRequest struct {
	Path   string `json:"path,omitempty"`
	Target string `json:"target,omitempty"`
}

type WriteFileResponse struct {
	Contents []byte `json:"contents,omitempty"`
}
