// Code generated by protoc-gen-plain-go. DO NOT EDIT.
package v1alpha1

// A single object housing all supported requests. All corresponding responses are of the same name on the Response object.
type Request struct {
	//  Metadata for the request.
	Metadata *RequestMetadata `json:"metadata,omitempty"`
	//  The schema data by name specified by the user. All available fields can be found in the "schema" field of the package.
	Data map[string]*Value `json:"data,omitempty"`
	//  Write a file to the user's machine.
	WriteFile *WriteFileRequest `json:"write_file,omitempty"`
}

type RequestMetadata struct {
	//  The name of the package that initiated the request.
	Package string `json:"package,omitempty"`
	//  The intended target specified in the package.
	Target string `json:"target,omitempty"`
	//  The path of the original plugin file in the package.
	Path string `json:"path,omitempty"`
}

type Value struct {
	String *string    `json:"string,omitempty"`
	Bool   *bool      `json:"bool,omitempty"`
	Number *float64   `json:"number,omitempty"`
	List   *ValueList `json:"list,omitempty"`
}

type ValueList struct {
	Strings []string  `json:"strings,omitempty"`
	Numbers []float64 `json:"numbers,omitempty"`
}

// A single object housing all supported responses.
type Response struct {
	WriteFile *WriteFileResponse `json:"write_file,omitempty"`
}

// Write a file to the user's machine.
type WriteFileRequest struct {
	//  The source path of this plugin.
	Path string `json:"path,omitempty"`
	//  The intended target filepath to be edited/created by this plugin.
	Target string `json:"target,omitempty"`
}

type WriteFileResponse struct {
	//  The new contents of the file.
	Contents []byte `json:"contents,omitempty"`
}
