// Code generated by protoc-gen-plain-go. DO NOT EDIT.
package v1alpha1

type Request struct {
	WriteFile *WriteFileRequest `json:"write_file"`
}

type Response struct {
	WriteFile *WriteFileResponse `json:"write_file"`
}

type WriteFileRequest struct {
	Path   string `json:"path"`
	Target string `json:"target"`
}

type WriteFileResponse struct {
	Contents []byte `json:"contents"`
}
