package main

import (
	"bytes"
	"embed"
	"io/fs"
	"path"
	"testing"

	"github.com/google/go-cmp/cmp"
	"github.com/stretchr/testify/suite"
	"google.golang.org/protobuf/proto"
	"google.golang.org/protobuf/testing/protocmp"
	"google.golang.org/protobuf/types/pluginpb"
)

type MainTestSuite struct {
	suite.Suite
}

//go:embed testdata/*
var testdata embed.FS

func (m *MainTestSuite) TestGenerate() {
	type test struct {
		GivenFileName string
		Expected      *pluginpb.CodeGeneratorResponse
	}

	tests := map[string]test{
		"simple": {
			GivenFileName: "plugin.bin",
			Expected: &pluginpb.CodeGeneratorResponse{
				SupportedFeatures: proto.Uint64(1),
				File: []*pluginpb.CodeGeneratorResponse_File{
					{
						Name:    proto.String("skiff/plugin/v1alpha1/plugin.plain.go"),
						Content: proto.String("// Code generated by protoc-gen-plain-go. DO NOT EDIT.\npackage v1alpha1\n\n\ntype WriteFileRequest struct {\n\t//  The source path of this plugin.\n\tPath string `json:\"path,omitempty\"`\n\t//  The intended target filepath to be edited/created by this plugin.\n\tTarget string `json:\"target,omitempty\"`\n}\n\ntype WriteFileResponse struct {\n\t//  The new contents of the file.\n\tContents []byte `json:\"contents,omitempty\"`\n}\n"),
					},
				},
			},
		},
	}

	for desc, v := range tests {
		m.Run(desc, func() {
			b, err := fs.ReadFile(testdata, path.Join("testdata", v.GivenFileName))
			if !m.NoError(err) {
				return
			}

			in, out := bytes.NewBuffer(b), bytes.NewBuffer(nil)
			err = generate(in, out)
			if !m.NoError(err) {
				return
			}

			resp := new(pluginpb.CodeGeneratorResponse)
			err = proto.Unmarshal(out.Bytes(), resp)
			if !m.NoError(err) {
				return
			}

			m.Empty(cmp.Diff(v.Expected, resp, protocmp.Transform()))
		})
	}
}

func TestMainTestSuite(t *testing.T) {
	suite.Run(t, new(MainTestSuite))
}
